name: Docker Image CI

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set image tag
      id: image_tag
      run: |
        TIMESTAMP=$(date +%s)
        IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/my-app:$TIMESTAMP"
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ steps.image_tag.outputs.IMAGE_NAME }}

    - name: Show image name
      run: |
        echo "::notice ::[Docker Build Success] Image created: ${{ steps.image_tag.outputs.IMAGE_NAME }}"

